### ISSUE TITLE
ENH: Instruments

### ISSUE THREAD

**Issue by sglyon** [gragusa/MomentBasedEstimators.jl#10]
We should expose an interface to the users where they can pass a moment function and an `Array{Float64, 2}` representing instruments. We could then define `_mf` as `kron(mf, instruments)`.

One way to do this would be to have the main version of `gmm` always accept a positional argument for the instruments and then have another method that that constructs a single column matrix of ones. This would incur overhead for computing the `kron(moments, ones)`, but it would be general. 

Thoughts welcome.

**Comment by gragusa** [comment]
This is more complicated than it seems.

We have

E[g_t \dot z_t]=0

Where g_t is (mx 1) and z_t is (r x 1).

But we passed g (n x m) and z (n x r).

So the kronecker product row-wise.

**Comment by sglyon** [comment]
Great catch. Implemented as part of #12
