### ISSUE TITLE
J-test

### ISSUE THREAD

**Issue by gragusa** [gragusa/MomentBasedEstimators.jl#13]
As of now, the J-test is calculated using the old weighting matrix, i.e., `J_test` calculates the statistics as the value of the objective function. This is fine --- asymptotically --- but it is common to update the weighting matrix using the parameter estimates of the last iteration (the idea being that since these estimators are efficient also the resulting inverse of the moment function should be efficient). 

I noticed that some other stat. packages uses flat out the objective function as J-test (namely Stata). I am however leaning toward using the updated objective the J-test. 

@spencerlyon2 what do you think?

**Comment by sglyon** [comment]
I think that's a great idea. I also vote we don't follow Stata and that we report the updated J_stat.

**Comment by sglyon** [comment]
See #15
