### ISSUE TITLE
Use IterationManagers.jl

### ISSUE THREAD

**Issue by sglyon** [gragusa/MomentBasedEstimators.jl#16]
I broke out the IterationManager part of this package and put it into its own package: https://github.com/spencerlyon2/IterationManagers.jl. 

As I use these routines in other code and have been updating the IterationManagers.jl package more regularly, I vote we use that package instead.

**Comment by gragusa** [comment]
GLTM

**Comment by gragusa** [comment]
Lgtm

**Comment by gragusa** [comment]
I think we should definitely do this.

**Comment by sglyon** [comment]
I started working on this and it wasn't as straightforward as I hoped it would be.

The problem is that we kinda have three states: the current parameter vector (theta), the current weighting matrix (W), and the current instance of the model (m). We would need to keep around (theta, W) because they are updated each iteration. We also like keeping around the model because we pull fields from it when we package up the result at the end of the function.

It was ending up being more work than it was worth for me to use the package. 

Do you have any suggestions?

**Comment by gragusa** [comment]
Oh. Ok I see. Probably better to keep things like this and focus on other
things.

**Comment by sglyon** [comment]
Sounds good to me. I'll close for now and put a "someday" tag on the issue.
