### ISSUE TITLE
Reduce verbosity of the default IpoptSolver

### ISSUE THREAD

**Issue by sglyon** [gragusa/MomentBasedEstimators.jl#20]
I find that the `Ipopt` printout produces a lot of clutter that Isn't necessarily relevant.

I would like to add `princ_level=2` to the keyword arguments for the default solver (i.e. have it be `IpoptSolver(hessian_approximation="limited-memory", print_level=2)`)  The documentation for options like this is supposedly [here](http://www.coin-or.org/Ipopt/documentation/node40.html#SECTION000111010000000000000), but I couldn't find a detailed description of what gets printed at each `print_level`. 

I chose 2 by decreasing from its default level of 5 until it didn't print out a bunch of stuff anymore.

**Comment by gragusa** [comment]
I agree

**Comment by sglyon** [comment]
Done
