### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by gragusa** [gragusa/MomentBasedEstimators.jl#22]
The package name `GMM.jl` is not appropriate for this package. We should probably switch to `GeneralizedMethodOfMoments.jl` which is very verbose, but it is descriptive enough.

Other possibilities is to go for `MethodOfMoments.jl`.

**Comment by sglyon** [comment]
What's wrong with GMM again? I just searched google and couldn't find the other GMM.jl package, so maybe we can have this name again?

**Comment by sglyon** [comment]
See JuliaLang/METADATA.jl#1642 for more comments about the name `GMM` in the julia-sphere.

**Comment by gragusa** [comment]
From that discussion it seems that `GMM.jl` is disputed territory. I agree  `GeneralizedMethodOfMoments.jl` is too long. But what then?

**Comment by sglyon** [comment]
Just listing some options... don't necessarily love any of them:
- `GenMoM.jl`
- `GeneralizedMoM.jl`
- `MoMs.jl` (if we merge with other moment estimators as we have discussed before)
- `MomentEstimators.jl` (same comment as above)
- `GenMethodOfMoments.jl`

**Comment by gragusa** [comment]
I am inclined to merge `MinimumDivergence.jl` into `GMM.jl`. But this will require some work on my side to uniform types. But even if we merge, not sure `MomentEstimators.jl` is the way to go --- it seems we are estimating moments and not parameters defined though moments. What about `MomentBasedEstimators.jl`?

**Comment by sglyon** [comment]
I like `MomentBasedEstimators.jl`

It is my favorite of the ones we have listed so far.

**Comment by gragusa** [comment]
Ok then `MomentBasedEstimators.jl` it is. Now this: do you know how a package name is supposed to take place? I know how to do it on github and then we should
- [x] change the module name
- [x] change .travis.yaml file
- [x] change coverall link
- [x] change readme
- [x] change `src/GMM.jl` to `src/MomentBasedEstimators.jl`
- [x] change `post_estimation` method signatures --- needed for merging `MinimumDivergence.jl`
- [x] change `using GMM` in runtest.jl
- [x] change `GMM.` to `MomentBasedEstimators.`

**Comment by sglyon** [comment]
since we aren't in METADATA yet this is a bit easier.

I think the only other thing we need to change (in addition to your list) is the main filename inside `src` from `GMM.jl` to `MomentBasedEstimators.jl`

**Comment by gragusa** [comment]
Should we change the abstract type `MomentEstimator` to `MomentBasedEstimator` as well?

**Comment by sglyon** [comment]
Yes, I like the consistency there.

**Comment by sglyon** [comment]
Ok, all PRs merged with tests still passing. I'll hold off on making additional changes until you have had a chance to work though this issue. let me know if I can help.

**Comment by gragusa** [comment]
I am doing it right now....

**Comment by gragusa** [comment]
I think I am done (although your moving `coeftable` from `api.jl` to `post_estimation.jl` throw me off ;-))
