### ISSUE TITLE
CLN: Package structure

### ISSUE THREAD

**Issue by sglyon** [gragusa/MomentBasedEstimators.jl#9]
It might be time to split the package into multiple files as mentioned in #5 

Here is a proposal, please comment:
- Keep main types in **GMM.jl** (`GMMNLPE`, `MomentEstimatorResult`, `GMMResult`, `MomentEstimator`, `GMMEstimator`, `IterationManager`,  `OneStepGMM`, `TwoStepGMM`, `IterativeGMM`, `IterationState`). We would also keep associated constructors, the `finished` methods, and the `show`/`writemime` methods.
- Move `MathProgBase` interface items to **gmm_mathprogbase.jl**
- Move `gmm` methods to **api.jl**
- Move post-estimation tools to **post_estimation.jl**. This includes `optimal_W`, `status`, `coef`, `objval`, `momentfunction`, `jacobian`, `mfvcov`, `nobs`, `npar`, `nmom`, `df`, `z_stats`, `p_values`, `shat`, `stderr`, and `J_test`

**Comment by gragusa** [comment]
LGTM

**Comment by sglyon** [comment]
Planning on implementing this this afternoon.

**Comment by sglyon** [comment]
See #19
